x-node_app: &node_app
  build:
    context: .
    dockerfile: ./docker/node/Dockerfile
  # ゾンビプロセス防止
  init: true
  volumes:
    - .:/develop

services:
  node:
    <<: *node_app
  next:
    <<: *node_app
    hostname: localhost
    ports:
      - 3000:3000
    restart: always
    command: pnpm run dev
  wrangler:
    # ゾンビプロセス防止
    init: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/wrangler/Dockerfile
    ports:
      - 8976:8976
      - 8788:8788
    volumes:
      - .:/develop
      - wrangler_config:/root/.config/.wrangler
    entrypoint: bash


volumes:
  wrangler_config:
