x-node_app: &node_app
  build:
    context: .
    dockerfile: ./docker/node/Dockerfile
  # ゾンビプロセス防止
  init: true
  volumes:
    - .:/develop
    - node_modules:/develop/node_modules

services:
  pnpm:
    <<: *node_app
    stdin_open: true
    entrypoint: bash
  next:
    <<: *node_app
    hostname: localhost
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/develop
      - wrangler_config:/root/.config/.wrangler
    command: pnpm run dev
  wrangler:
    # ゾンビプロセス防止
    init: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 8976:8976
      - 8788:8788
    volumes:
      - .:/develop
      - wrangler_config:/root/.config/.wrangler
    entrypoint: bash


volumes:
  wrangler_config:
  node_modules:
